

onlyBuiltDependencies:
- "@biomejs/biome"
- "lefthook"

packages:
  - 'examples/*'

verifyDepsBeforeRun: 'install'

catalog:
  '@tailwindcss/vite': 4.1.17
  '@tonconnect/ui-react': 2.3.1
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@vitejs/plugin-react': 5.0.4
  'react': 19.1.2
  'react-dom': 19.1.2
  'tailwindcss': 4.1.17
  'vite': 7.2.2

